Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pizza.cs
namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public double Price { get; set; }

        public Pizza(string name, string description, string image, double price)
        {
            Name = name;
            Description = description;
            Image = image;
            Price = price;
        }
    }
}

Controllers/EserciziController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class EserciziController : Controller
    {
        private readonly ILogger<EserciziController> _logger;

        public EserciziController(ILogger<EserciziController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzasController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzasController : Controller
    {

        public List<Pizza> Pizzas()
        {
            List<Pizza> pizzas = new()
            {
                new Pizza("Margherita", "La pizza Margherita", "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800_fallback/public/fdl_content_import_it/margherita-50kalo.jpg?itok=v9nHxNMS", 10.50),
                new Pizza("Napoli", "La pizza Napoli", "https://media-cdn.tripadvisor.com/media/photo-s/18/03/98/d6/received-665664433902722.jpg", 14.50),
                new Pizza("Romana", "La pizza Romana", "https://recipesblob.oetker.com/files/95bdfe7334364b41b557c734cd1c64c4/889e39b112414a9aa2b3ae5a9f787f6b/1272x764/pizza-alla-romanajpg.jpg", 17.50),
                new Pizza("4 Gusti", "La pizza 4 Gusti", "https://media-cdn.tripadvisor.com/media/photo-s/07/61/12/f1/pizza-4-gusti.jpg", 5.50)
            };
            return pizzas;
        }

        public IActionResult Index()
        {
            return View(Pizzas());
        }
        public IActionResult Show(int id)
        {
            return View(Pizzas()[id]);
        }

    }
}

Views/Esercizi/Index.cshtml
@{
    Layout = "Esercizi/_Layout";

    //   1. Dichiarare una variabile valorizzandola con il nostro nome.
    //Dichiarare un'altra variabile valorizzandola con il nostro cognome.
    //Stampare il nostro nome e cognome all'interno di un tag h2.

    string name = "Manuel";
    string surname = "Benini";

    //    2.Creare una funzione che stampa la somma dei numeri che vanno da 1 a n(con n passato come parametro -n incluso)
    //Stampare dentro uno span il risultato.

    int SommaNumeri(int n)
    {

        int sum = 0;
        for (int i = 1; i <= n; i++)
        {
            sum += i;
        }

        return sum;
    }

    //3. Contare quante volte la lettera a è presente nella frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina

    string source = "nel mezzo del cammin di nostra vita";
    int count = 0;

    foreach (char a in source)
    {
        if (a == 'a')
        {
            count++;
        }
    }

    //4. Creare una List<int> di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70

    Random rnd = new Random();
    List<int> randomNumbersList = new List<int>();

    for (int i = 0; i < 20; i++)
    {
        randomNumbersList.Add(rnd.Next(1, 91));
    }

    //5. Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi

    //    6. Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina
    //a. la data di 7 giorni fa
    //b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
    //c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
}

 <h2 class="display-4">Esercizio 1: @name @surname</h2>

 <h4>Esercizio 2: @SommaNumeri(5)</h4>

<h4>Esercizio 3: Numero di "a" presenti nella frase "nel mezzo del cammin di nostra vita": @count</h4>

<h4>Esercizio 4: Numeri compresi tra 20 e 70 inclusi nella lista</h4>

<ul>
    @foreach (int number in randomNumbersList)
    {
        @if (number > 19 && number < 71)
        {
            <li>@number</li>
        }
    }
</ul>

<h4>Esercizio 5: data attuale => @DateTime.Now.ToString("yyyy'-'MM'-'dd' 'HH':'mm':'ss")</h4>

<h4>Esercizio 6a: data 7 giorni fa => @DateTime.Now.AddDays(-7).ToString("yyyy'-'MM'-'dd' 'HH':'mm':'ss")</h4>

<h4>Esercizio 6b: giorno della settimana attuale => @DateTime.Now.ToString("dddd")</h4>

<h4>Esercizio 6c: giorno della settimana tra un anno => @DateTime.Now.AddYears(1).ToString("dddd")</h4>

Views/Pizzas/Index.cshtml
@model List<Pizza>
@{
    int count = 0;
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Image</th>
            <th scope="col">price</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            @foreach (Pizza pizza in Model)
            {
                <tr>
                    <th>@pizza.Name</th>
                    <td>@pizza.Description</td>
                    <td> <img src="@pizza.Image" alt="Immagine della pizza"> </td>
                    <td>@pizza.Price&euro;</td>
                    <td> <a href="@Url.Action("Show", "Pizzas", new {id = count++})">Go to the detail</a> </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <th>Nessuna pizza disponibile</th>
            </tr>
        }
        
        
    </tbody>
</table>

Views/Pizzas/Show.cshtml
@model Pizza

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Image</th>
            <th scope="col">price</th>
        </tr>
    </thead>
    <tbody>

            <tr>
                <th>@Model.Name</th>
                <td>@Model.Description</td>
                <td> <img src="@Model.Image" alt="Immagine della pizza"> </td>
                <td>@Model.Price&euro;</td>
            </tr>

    </tbody>
</table>

Views/Shared/Esercizi/_Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

Views/Shared/Esercizi/_Head.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>

Views/Shared/Esercizi/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Views/Shared/Esercizi/_Layout.cshtml
@Html.Partial("Esercizi/_Head");


<body>
    @Html.Partial("Esercizi/_Header");

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @Html.Partial("Esercizi/_Footer");

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Esercizi" asp-action="Index">Esercizi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>